// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoTest.proto

#ifndef PROTOBUF_ProtoTest_2eproto__INCLUDED
#define PROTOBUF_ProtoTest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ProtoTest_2eproto();
void protobuf_AssignDesc_ProtoTest_2eproto();
void protobuf_ShutdownFile_ProtoTest_2eproto();

class ProtoTest;

// ===================================================================

class ProtoTest : public ::google::protobuf::Message {
 public:
  ProtoTest();
  virtual ~ProtoTest();

  ProtoTest(const ProtoTest& from);

  inline ProtoTest& operator=(const ProtoTest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoTest& default_instance();

  void Swap(ProtoTest* other);

  // implements Message ----------------------------------------------

  ProtoTest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoTest& from);
  void MergeFrom(const ProtoTest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 int32_value = 1;
  inline bool has_int32_value() const;
  inline void clear_int32_value();
  static const int kInt32ValueFieldNumber = 1;
  inline ::google::protobuf::int32 int32_value() const;
  inline void set_int32_value(::google::protobuf::int32 value);

  // optional string string_value = 2;
  inline bool has_string_value() const;
  inline void clear_string_value();
  static const int kStringValueFieldNumber = 2;
  inline const ::std::string& string_value() const;
  inline void set_string_value(const ::std::string& value);
  inline void set_string_value(const char* value);
  inline void set_string_value(const char* value, size_t size);
  inline ::std::string* mutable_string_value();
  inline ::std::string* release_string_value();
  inline void set_allocated_string_value(::std::string* string_value);

  // repeated int32 rpt_int32_value = 3;
  inline int rpt_int32_value_size() const;
  inline void clear_rpt_int32_value();
  static const int kRptInt32ValueFieldNumber = 3;
  inline ::google::protobuf::int32 rpt_int32_value(int index) const;
  inline void set_rpt_int32_value(int index, ::google::protobuf::int32 value);
  inline void add_rpt_int32_value(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      rpt_int32_value() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_rpt_int32_value();

  // repeated string rpt_string_value = 4;
  inline int rpt_string_value_size() const;
  inline void clear_rpt_string_value();
  static const int kRptStringValueFieldNumber = 4;
  inline const ::std::string& rpt_string_value(int index) const;
  inline ::std::string* mutable_rpt_string_value(int index);
  inline void set_rpt_string_value(int index, const ::std::string& value);
  inline void set_rpt_string_value(int index, const char* value);
  inline void set_rpt_string_value(int index, const char* value, size_t size);
  inline ::std::string* add_rpt_string_value();
  inline void add_rpt_string_value(const ::std::string& value);
  inline void add_rpt_string_value(const char* value);
  inline void add_rpt_string_value(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& rpt_string_value() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_rpt_string_value();

  // @@protoc_insertion_point(class_scope:ProtoTest)
 private:
  inline void set_has_int32_value();
  inline void clear_has_int32_value();
  inline void set_has_string_value();
  inline void clear_has_string_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* string_value_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > rpt_int32_value_;
  ::google::protobuf::RepeatedPtrField< ::std::string> rpt_string_value_;
  ::google::protobuf::int32 int32_value_;
  friend void  protobuf_AddDesc_ProtoTest_2eproto();
  friend void protobuf_AssignDesc_ProtoTest_2eproto();
  friend void protobuf_ShutdownFile_ProtoTest_2eproto();

  void InitAsDefaultInstance();
  static ProtoTest* default_instance_;
};
// ===================================================================


// ===================================================================

// ProtoTest

// optional int32 int32_value = 1;
inline bool ProtoTest::has_int32_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoTest::set_has_int32_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoTest::clear_has_int32_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoTest::clear_int32_value() {
  int32_value_ = 0;
  clear_has_int32_value();
}
inline ::google::protobuf::int32 ProtoTest::int32_value() const {
  // @@protoc_insertion_point(field_get:ProtoTest.int32_value)
  return int32_value_;
}
inline void ProtoTest::set_int32_value(::google::protobuf::int32 value) {
  set_has_int32_value();
  int32_value_ = value;
  // @@protoc_insertion_point(field_set:ProtoTest.int32_value)
}

// optional string string_value = 2;
inline bool ProtoTest::has_string_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoTest::set_has_string_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoTest::clear_has_string_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoTest::clear_string_value() {
  if (string_value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_value_->clear();
  }
  clear_has_string_value();
}
inline const ::std::string& ProtoTest::string_value() const {
  // @@protoc_insertion_point(field_get:ProtoTest.string_value)
  return *string_value_;
}
inline void ProtoTest::set_string_value(const ::std::string& value) {
  set_has_string_value();
  if (string_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_value_ = new ::std::string;
  }
  string_value_->assign(value);
  // @@protoc_insertion_point(field_set:ProtoTest.string_value)
}
inline void ProtoTest::set_string_value(const char* value) {
  set_has_string_value();
  if (string_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_value_ = new ::std::string;
  }
  string_value_->assign(value);
  // @@protoc_insertion_point(field_set_char:ProtoTest.string_value)
}
inline void ProtoTest::set_string_value(const char* value, size_t size) {
  set_has_string_value();
  if (string_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_value_ = new ::std::string;
  }
  string_value_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ProtoTest.string_value)
}
inline ::std::string* ProtoTest::mutable_string_value() {
  set_has_string_value();
  if (string_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_value_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:ProtoTest.string_value)
  return string_value_;
}
inline ::std::string* ProtoTest::release_string_value() {
  clear_has_string_value();
  if (string_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = string_value_;
    string_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ProtoTest::set_allocated_string_value(::std::string* string_value) {
  if (string_value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete string_value_;
  }
  if (string_value) {
    set_has_string_value();
    string_value_ = string_value;
  } else {
    clear_has_string_value();
    string_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:ProtoTest.string_value)
}

// repeated int32 rpt_int32_value = 3;
inline int ProtoTest::rpt_int32_value_size() const {
  return rpt_int32_value_.size();
}
inline void ProtoTest::clear_rpt_int32_value() {
  rpt_int32_value_.Clear();
}
inline ::google::protobuf::int32 ProtoTest::rpt_int32_value(int index) const {
  // @@protoc_insertion_point(field_get:ProtoTest.rpt_int32_value)
  return rpt_int32_value_.Get(index);
}
inline void ProtoTest::set_rpt_int32_value(int index, ::google::protobuf::int32 value) {
  rpt_int32_value_.Set(index, value);
  // @@protoc_insertion_point(field_set:ProtoTest.rpt_int32_value)
}
inline void ProtoTest::add_rpt_int32_value(::google::protobuf::int32 value) {
  rpt_int32_value_.Add(value);
  // @@protoc_insertion_point(field_add:ProtoTest.rpt_int32_value)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ProtoTest::rpt_int32_value() const {
  // @@protoc_insertion_point(field_list:ProtoTest.rpt_int32_value)
  return rpt_int32_value_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ProtoTest::mutable_rpt_int32_value() {
  // @@protoc_insertion_point(field_mutable_list:ProtoTest.rpt_int32_value)
  return &rpt_int32_value_;
}

// repeated string rpt_string_value = 4;
inline int ProtoTest::rpt_string_value_size() const {
  return rpt_string_value_.size();
}
inline void ProtoTest::clear_rpt_string_value() {
  rpt_string_value_.Clear();
}
inline const ::std::string& ProtoTest::rpt_string_value(int index) const {
  // @@protoc_insertion_point(field_get:ProtoTest.rpt_string_value)
  return rpt_string_value_.Get(index);
}
inline ::std::string* ProtoTest::mutable_rpt_string_value(int index) {
  // @@protoc_insertion_point(field_mutable:ProtoTest.rpt_string_value)
  return rpt_string_value_.Mutable(index);
}
inline void ProtoTest::set_rpt_string_value(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:ProtoTest.rpt_string_value)
  rpt_string_value_.Mutable(index)->assign(value);
}
inline void ProtoTest::set_rpt_string_value(int index, const char* value) {
  rpt_string_value_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ProtoTest.rpt_string_value)
}
inline void ProtoTest::set_rpt_string_value(int index, const char* value, size_t size) {
  rpt_string_value_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ProtoTest.rpt_string_value)
}
inline ::std::string* ProtoTest::add_rpt_string_value() {
  return rpt_string_value_.Add();
}
inline void ProtoTest::add_rpt_string_value(const ::std::string& value) {
  rpt_string_value_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ProtoTest.rpt_string_value)
}
inline void ProtoTest::add_rpt_string_value(const char* value) {
  rpt_string_value_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ProtoTest.rpt_string_value)
}
inline void ProtoTest::add_rpt_string_value(const char* value, size_t size) {
  rpt_string_value_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ProtoTest.rpt_string_value)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ProtoTest::rpt_string_value() const {
  // @@protoc_insertion_point(field_list:ProtoTest.rpt_string_value)
  return rpt_string_value_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ProtoTest::mutable_rpt_string_value() {
  // @@protoc_insertion_point(field_mutable_list:ProtoTest.rpt_string_value)
  return &rpt_string_value_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProtoTest_2eproto__INCLUDED
